version: '3.8'

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: joy_music
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_pass
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
    container_name: app1
    environment:
      SPRING_APPLICATION_NAME: music-app
      SPRING_PROFILES_ACTIVE: prod
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/joy_music
      SPRING_DATASOURCE_USERNAME: music_user
      SPRING_DATASOURCE_PASSWORD: music_pass
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    expose:
      - "8080"
    depends_on:
      - redis
      - postgres
    networks:
      - backend

  app2:
    build:
      context: .
    container_name: app2
    environment:
      SPRING_APPLICATION_NAME: music-app
      SPRING_PROFILES_ACTIVE: prod
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/joy_music
      SPRING_DATASOURCE_USERNAME: music_user
      SPRING_DATASOURCE_PASSWORD: music_pass
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    expose:
      - "8080"
    depends_on:
      - redis
      - postgres
    networks:
      - backend

  nginx:
    container_name: proxy-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
      - app2
    networks:
      - backend

  prometheus:
    build:
      context: ./prometheus
      dockerfile: dockerfile
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app
      - app2
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend: