CREATE TABLE IF NOT EXISTS artist  (
                        id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        external_identifier VARCHAR(255) UNIQUE NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS  track (
                       id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       genre VARCHAR(100),
                       length_in_seconds INT,
                       artist_id BIGINT,
                       CONSTRAINT fk_track_artist FOREIGN KEY (artist_id) REFERENCES artist(id) ON DELETE CASCADE
);